using System.Runtime.InteropServices;
using FloatingTransferStation.Services;

namespace FloatingTransferStation.Mac.Services;

public sealed record PasteboardState(long ChangeCount, IReadOnlyList<string> Types)
{
    public bool IsPrivate => Types.Any(MacPasteboard.IsExcludedType);
    public bool HasFiles => Types.Contains("public.file-url");
}

public interface IPasteboardStateReader
{
    PasteboardState ReadState();
}

/// <summary>Small Objective-C bridge; no macOS .NET workload or accessibility permission is needed.</summary>
public sealed class MacPasteboard : IPasteboardStateReader
{
    private const string ObjectiveC = "/usr/lib/libobjc.A.dylib";
    private static readonly HashSet<string> ExcludedTypes = new(StringComparer.Ordinal)
    {
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "Pasteboard generator type",
        "com.agilebits.onepassword"
    };

    public static bool IsExcludedType(string type) => ExcludedTypes.Contains(type);

    public PasteboardState ReadState()
    {
        EnsureMacOS();
        using var pool = new AutoreleasePool();
        var board = GeneralPasteboard();
        var count = SendInteger(board, Selector("changeCount"));
        var types = ReadTypes(Send(board, Selector("types")));
        if (count != SendInteger(board, Selector("changeCount")))
        {
            throw new IOException("The pasteboard changed while its types were being read.");
        }

        return new PasteboardState(count, types);
    }

    // Avalonia maps public.png to a decoded Bitmap. Read original NSData here so limits are
    // applied before decoding, preserving EXIF and all alternative representations.
    public TransferPayload? ReadImages(PasteboardState state, ImageInputLimits? limits = null)
    {
        EnsureMacOS();
        if (state.IsPrivate || state.HasFiles || !state.Types.Any(AvaloniaTransferReader.IsEncodedImageFormat))
        {
            return null;
        }

        var budget = limits ?? ImageInputLimits.Default;
        using var pool = new AutoreleasePool();
        var board = GeneralPasteboard();
        EnsureCurrent(board, state.ChangeCount);
        var items = Send(board, Selector("pasteboardItems"));
        var itemCount = SendInteger(items, Selector("count"));
        if (itemCount > AvaloniaTransferReader.MaximumItems)
        {
            throw new ImageInputLimitException("Too many images in one clipboard transfer.");
        }

        var images = new List<TransferPayload.ImageCandidates>();
        ImageInputLimitException? failure = null;
        long totalBytes = 0;
        for (nint index = 0; index < itemCount; index++)
        {
            var item = SendIndex(items, Selector("objectAtIndex:"), index);
            var types = ReadTypes(Send(item, Selector("types")));
            var candidates = new List<ReadOnlyMemory<byte>>();
            foreach (var type in types.Where(AvaloniaTransferReader.IsEncodedImageFormat))
            {
                EnsureCurrent(board, state.ChangeCount);
                var nativeType = SendString(GetClass("NSString"), Selector("stringWithUTF8String:"), type);
                var data = SendPointer(item, Selector("dataForType:"), nativeType);
                var length = SendInteger(data, Selector("length"));
                if (length <= 0)
                {
                    continue;
                }

                try
                {
                    budget.ValidateEncodedLength(length);
                    if (totalBytes + length > AvaloniaTransferReader.MaximumSnapshotBytes)
                    {
                        throw new ImageInputLimitException("Clipboard snapshot exceeds the memory budget.");
                    }

                    var bytes = new byte[checked((int)length)];
                    Marshal.Copy(Send(data, Selector("bytes")), bytes, 0, bytes.Length);
                    totalBytes += length;
                    candidates.Add(bytes);
                }
                catch (ImageInputLimitException exception)
                {
                    failure ??= exception;
                }
            }

            if (candidates.Count > 0)
            {
                images.Add(new TransferPayload.ImageCandidates(candidates));
            }
        }

        EnsureCurrent(board, state.ChangeCount);
        if (images.Count > 0)
        {
            return images.Count == 1 ? images[0] : new TransferPayload.ImageBatch(images);
        }

        if (failure is not null)
        {
            throw failure;
        }

        return null;
    }

    private static string[] ReadTypes(nint array)
    {
        var count = SendInteger(array, Selector("count"));
        var result = new string[checked((int)count)];
        for (var index = 0; index < result.Length; index++)
        {
            var value = SendIndex(array, Selector("objectAtIndex:"), index);
            result[index] = Marshal.PtrToStringUTF8(Send(value, Selector("UTF8String"))) ?? string.Empty;
        }

        return result;
    }

    private static nint GeneralPasteboard() => Send(GetClass("NSPasteboard"), Selector("generalPasteboard"));

    private static void EnsureCurrent(nint board, long count)
    {
        if (SendInteger(board, Selector("changeCount")) != count)
        {
            throw new IOException("The clipboard content changed during capture.");
        }
    }

    private static void EnsureMacOS()
    {
        if (!OperatingSystem.IsMacOS())
        {
            throw new PlatformNotSupportedException("NSPasteboard is only available on macOS.");
        }
    }

    private sealed class AutoreleasePool : IDisposable
    {
        private readonly nint _pool = Send(Send(GetClass("NSAutoreleasePool"), Selector("alloc")), Selector("init"));
        public void Dispose() => Send(_pool, Selector("drain"));
    }

    [DllImport(ObjectiveC, EntryPoint = "objc_getClass")]
    private static extern nint GetClass([MarshalAs(UnmanagedType.LPUTF8Str)] string name);
    [DllImport(ObjectiveC, EntryPoint = "sel_registerName")]
    private static extern nint Selector([MarshalAs(UnmanagedType.LPUTF8Str)] string name);
    [DllImport(ObjectiveC, EntryPoint = "objc_msgSend")]
    private static extern nint Send(nint receiver, nint selector);
    [DllImport(ObjectiveC, EntryPoint = "objc_msgSend")]
    private static extern nint SendInteger(nint receiver, nint selector);
    [DllImport(ObjectiveC, EntryPoint = "objc_msgSend")]
    private static extern nint SendIndex(nint receiver, nint selector, nint index);
    [DllImport(ObjectiveC, EntryPoint = "objc_msgSend")]
    private static extern nint SendPointer(nint receiver, nint selector, nint value);
    [DllImport(ObjectiveC, EntryPoint = "objc_msgSend")]
    private static extern nint SendString(nint receiver, nint selector, [MarshalAs(UnmanagedType.LPUTF8Str)] string value);
}
