using Avalonia.Input;
using FloatingTransferStation.Mac.Services;
using FloatingTransferStation.Services;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FloatingTransferStation.Mac.Tests.Services;

[TestClass]
public sealed class AvaloniaTransferReaderTests
{
    [TestMethod]
    public async Task Read_ThrowingImageFormatDoesNotHideOtherRepresentation()
    {
        var png = DataFormat.CreateBytesPlatformFormat("public.png");
        var tiff = DataFormat.CreateBytesPlatformFormat("public.tiff");
        var item = new DataTransferItem();
        item.Set(png, () => throw new IOException("unavailable"));
        item.Set(tiff, new byte[] { 1, 2, 3 });
        using IAsyncDataTransfer data = Transfer(item);

        var payload = await new AvaloniaTransferReader().ReadAsync(data);

        var images = Assert.IsInstanceOfType<TransferPayload.ImageCandidates>(payload);
        CollectionAssert.AreEqual(new byte[] { 1, 2, 3 }, images.Candidates.Single().ToArray());
    }

    [TestMethod]
    public async Task Read_FailedFilePayloadNeverFallsBackToPathText()
    {
        var item = new DataTransferItem();
        item.Set(DataFormat.File, () => throw new FileNotFoundException());
        item.SetText("/Users/test/missing.png");
        using IAsyncDataTransfer data = Transfer(item);

        Assert.IsNull(await new AvaloniaTransferReader().ReadAsync(data));
    }

    [TestMethod]
    public async Task Read_CopiesImageBytesBeforeSourceIsDisposedOrModified()
    {
        byte[] original = [1, 2, 3];
        var item = DataTransferItem.Create(DataFormat.CreateBytesPlatformFormat("public.png"), original);
        using IAsyncDataTransfer data = Transfer(item);
        var payload = Assert.IsInstanceOfType<TransferPayload.ImageCandidates>(await new AvaloniaTransferReader().ReadAsync(data));

        original[0] = 99;

        Assert.AreEqual((byte)1, payload.Candidates[0].Span[0]);
    }

    [TestMethod]
    public async Task Read_ByteLimitStillAllowsAnotherSmallRepresentation()
    {
        var item = new DataTransferItem();
        item.Set(DataFormat.CreateBytesPlatformFormat("public.png"), new byte[10]);
        item.Set(DataFormat.CreateBytesPlatformFormat("public.tiff"), new byte[3]);
        using IAsyncDataTransfer data = Transfer(item);

        var payload = Assert.IsInstanceOfType<TransferPayload.ImageCandidates>(
            await new AvaloniaTransferReader(new ImageInputLimits(MaxEncodedBytes: 4)).ReadAsync(data));

        Assert.AreEqual(3, payload.Candidates.Single().Length);
    }

    [TestMethod]
    public async Task Read_MultipleClipboardItemsKeepIndependentRepresentationGroups()
    {
        var png = DataFormat.CreateBytesPlatformFormat("public.png");
        using IAsyncDataTransfer data = Transfer(DataTransferItem.Create(png, new byte[] { 1 }),
            DataTransferItem.Create(png, new byte[] { 2 }));
        var batch = Assert.IsInstanceOfType<TransferPayload.ImageBatch>(await new AvaloniaTransferReader().ReadAsync(data));

        Assert.AreEqual((byte)1, batch.Images[0].Candidates[0].Span[0]);
        Assert.AreEqual((byte)2, batch.Images[1].Candidates[0].Span[0]);
    }

    [TestMethod]
    public async Task Read_SynchronousDropPreservesTextWhitespace()
    {
        using IDataTransfer data = Transfer(DataTransferItem.CreateText("  multiline\nvalue  "));
        var text = Assert.IsInstanceOfType<TransferPayload.Text>(await new AvaloniaTransferReader().ReadAsync(data));
        Assert.AreEqual("  multiline\nvalue  ", text.Value);
    }

    [TestMethod]
    [DataRow("org.nspasteboard.ConcealedType")]
    [DataRow("org.nspasteboard.TransientType")]
    [DataRow("org.nspasteboard.AutoGeneratedType")]
    [DataRow("com.agilebits.onepassword")]
    public void PasteboardState_ExcludesSensitiveAndTransientMarkers(string marker)
    {
        Assert.IsTrue(new PasteboardState(7, ["public.utf8-plain-text", marker]).IsPrivate);
        Assert.IsFalse(new PasteboardState(8, ["public.utf8-plain-text"]).IsPrivate);
    }

    private static DataTransfer Transfer(params DataTransferItem[] items)
    {
        var data = new DataTransfer();
        foreach (var item in items)
        {
            data.Add(item);
        }

        return data;
    }
}
